### PR TITLE
feat(Issue#1): added text when the map data is loading

### PR DESCRIPTION
**Pull request by Uzaif-Sheikh**
In order to add loading text when the map is being loaded, I'm checking if the map in the state object is undefined than show the loading text.
```JavaScript
{state.map === undefined && <LoadingTag>Loading data...</LoadingTag>}
```
For the loading text, I thought of keeping it at the top center.

image

### CODE REVIEW

**Comment by jakecoppinger** [comment]
Thanks for the PR!

I haven't checked this out locally but my first thought is that this might only display when the map itself is loading, but the data that drives the pins hasn't arrived yet.

As the call for the timing data takes the longest should we change this to switch on `state.points` instead of `state.map`?

**Comment by Uzaif-Sheikh** [comment]
Hi Jake, I have pushed the changes for showing the loading text when points are loading in the map and this how it looks now:

image

**Comment by jakecoppinger** [comment]
Brilliant, thanks! Will deploy soon.
Sorry for the delay, I'm moving house next week.

**Comment by jakecoppinger** [comment]
Screen Shot 2023-08-30 at 23 29 25

Deployed to prod 🎉

**Comment by Uzaif-Sheikh** [comment]
Hi Jake, all good no worries :). Thanks for merging the PR.

**Pull request merged**
